dataset:
  test_size: 0.2
  random_state: 42
  rename_columns:
    customer_id: customer_id
    date: date
    transaction_type: transaction_type
    description: description
    deposit: deposit
    withdrawal: withdrawal
    balance: balance
features:
  fs: 1.0
  nperseg: 64
  noverlap: 0
  bins: 33
modeling:
  model_type: random_forest
  n_estimators: 100
  columns_to_drop:
    - customer_id
    - target
  target: target  